site_name: eGeoffrey Developer Portal
site_url: https://www.egeoffrey.com
repo_url: https://www.egeoffrey.com/#resources
repo_name: egeoffrey.com
nav:
- Home: index.md
- Learn: 
  - Design: learn/design.md
  - Definitions: learn/definitions.md
  - Architecture: learn/architecture.md
  - Components:
    - Controller: learn/components/controller.md
    - Gateway: learn/components/gateway.md
    - Database: learn/components/database.md
    - Web UI: learn/components/gui.md
    - Mobile App: learn/components/mobile.md
  - How it works: learn/how-it-works.md
  - Configuration: learn/configuration.md
  - Security: learn/security.md
  - Multi-Tenancy: learn/multi-tenancy.md
  - Deployment Options: learn/deployment.md
  - Manifest File: learn/manifest.md
  - Versioning: learn/versioning.md
  - Upgrading: learn/upgrading.md
- Develop & Build:  
  - Overview: develop/overview.md
  - Develop: develop/develop.md
  - Build: develop/build.md
  - Distribute: develop/distribute.md

- SDK:
  - Overview: sdk/overview.md
  - Classes:
    - Module: sdk/classes/module.md
    - Message: sdk/classes/message.md
    - Session: sdk/classes/session.md
    - Mqtt_client: sdk/classes/mqtt_client.md
    - Scheduler: sdk/classes/scheduler.md
    - Cache: sdk/classes/cache.md
  - Utils:
    - Command: sdk/utils/command.md
    - DateTimeUtils: sdk/utils/datetimeutils.md
    - Exceptions: sdk/utils/exceptions.md
    - Numbers: sdk/utils/numbers.md
    - Strings: sdk/utils/strings.md
    - Web: sdk/utils/web.md
- Tools:
  - egeoffrey-cli: tools/cli.md
  - egeoffrey-installer: tools/installer.md
google_analytics: ['UA-1633536-6', 'developer.egeoffrey.com']
theme: 
  name: material
extra_css:
  - css/custom.css