site_name: eGeoffrey Developer Portal
site_url: https://www.egeoffrey.com
#repo_url: https://www.egeoffrey.com/#resources
#repo_name: www.egeoffrey.com
nav:
- Home: index.md
- Learn: 
  - Design: learn/design.md
  - Definitions: learn/definitions.md
  - Architecture: learn/architecture.md
  - Components:
    - Controller: learn/components/controller.md
    - Gateway: learn/components/gateway.md
    - Database: learn/components/database.md
    - Web UI: learn/components/gui.md
  - How it works: learn/how-it-works.md
  - Configuration: learn/configuration.md
  - Security: learn/security.md
  - Multi-Tenancy: learn/multi-tenancy.md
  - Deployment Options: learn/deployment.md
- Develop:  
  - Overview: develop/overview.md
  - eGeoffrey SDK: develop/sdk.md
  - Classes:
    - Module: develop/classes/module.md
    - Message: develop/classes/message.md
    - Session: develop/classes/session.md
    - Mqtt_client: develop/classes/mqtt_client.md
    - Scheduler: develop/classes/scheduler.md
    - Cache: develop/classes/cache.md
  - Utils: 
    - Command: develop/utils/command.md
    - DateTimeUtils: develop/utils/datetimeutils.md
    - Exceptions: develop/utils/exceptions.md
    - Numbers: develop/utils/numbers.md
    - Strings: develop/utils/strings.md
    - Web: develop/utils/web.md
- Build: 
  - Overview: build/overview.md
  - Manifest: build/manifest.md
  - Versioning: build/versioning.md
  - Updating: build/updating.md
- Distribute: 
  - Marketplace: distribute/marketplace.md
- Tools:
  - egeoffrey-cli: tools/cli.md
  - egeoffrey-installer: tools/installer.md
theme: 
  name: cinder
